version: "3"
services:
  bot:
    build: bot/
    command: python ./main.py
    ports:
      - 5432:5432

  informer:
    build: tiktokinformer/
    command: python ./main.py
    ports:
      - 5432:5432