version: "3"
services:
  bot:
    build: bot/
    container_name: tiktokinformer_bot
    command: python3 ./main.py

  informer:
    build: tiktokinformer/
    container_name: tiktokinformer_informer
    command: python3 ./main.py
    depends_on: 
      - bot
